### ISSUE TITLE
AN00231: 192kHz operation

### ISSUE THREAD

**Issue by larry-xmos** [xmos/lib_src#17]
Quinn reported problems running the app note configured to 192kHz (coaxial S/PDIF)

See RT ticket 9788 for more details

**Comment by ed-xmos** [comment]
The app note was not designed to run at 192KHz. From the document (4th paragraph)

"The sample rates supported for this demonstration are 44.1, 48, 88.2 and 96KHz. This restriction is applied by the SPDIF receiver which is only rated up to 96KHz for optical sources and the ASRC library which can currently only handle rates of 176.4/192KHz on one side. The restricted sample rates also allow significant chip resource usage optimization which is discussed later within this application note."

I think it could be modified to support this with one or more of the following considerations:

- 192KHz SPDIF source would need to be very low jitter (coax)
- Use i2s_frame_master instead of i2s_master to reduce backpressure on the I2S side
- change buffering to non-distributable
